#!/bin/sh
unset NODE_OPTIONS
ELECTRON_RUN_AS_NODE=1 "/nix/store/kdp9ssbgrgrnifjpha3pxbdpxb36pyay-vscode-1.129.1/lib/vscode/code" "/home/leo/.config/Code/User/globalStorage/github.copilot-chat/copilotCli/copilotCLIShim.js" "$@"