[General]
codecs-profiles-selected=
filedialog-path=@Variant(\0\0\0\x11\0\0\0\t/home/leo)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x3\xc6\0\0\0\x30\0\0\ai\0\0\x2\"\0\0\x3\xc6\0\0\0\x30\0\0\ai\0\0\x2\"\0\0\0\0\0\0\0\0\a\x80\0\0\x3\xc6\0\0\0\x30\0\0\ai\0\0\x2\")

[FullScreen]
pos=@Point(560 1015)
screen=@Rect(0 0 1920 1080)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(932 422)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[OpenDialog]
advanced=false
netMRL=https://iptv-org.github.io/iptv/index.m3u
size=@Size(557 443)

[RecentsMRL]
list=file:///run/media/leo/DE00-80CA/Funerals/joel/LNO%20Funeral%20Service%20Intro%281%29.mp4, file:///home/leo/Downloads/LNO%20Stay%20Tuned%20-%20F.mp4, file:///home/leo/Downloads/LNO%20Funeral%20Service%20Intro.mp4, file:///home/leo/Downloads/Copy%20of%20Copy%20of%20life%20in%20photos%20.mp4, file:///home/leo/Downloads/Copy%20of%20LNO%20Lower%20Thirds.mp4, file:///home/leo/Downloads/Thank%20You.mp4, file:///home/leo/Videos/obs/2026-07-13_20-39-46.mkv, file:///run/media/leo/DE00-80CA/PRIVATE/AVCHD/BDMV/STREAM/00013.MTS, file:///run/media/leo/DE00-80CA/PRIVATE/AVCHD/BDMV/STREAM/00001.MTS, https://123tv-mx1.flex-cdn.net/index.m3u8, https://dash2.antik.sk/live/1plus1_marathon/playlist.m3u8, https://dash2.antik.sk/live/test_one_plus_one_int_tizen/playlist.m3u8, https://jmp2.uk/plu-62ba60f059624e000781c436.m3u8, https://iptv-org.github.io/iptv/index.m3u, file:///home/leo/Downloads/Funeral%20Marylin%20Theodore%20%E2%80%9CCoolie%E2%80%9D/Copy%20of%20Copy%20of%20life%20in%20photos%20.mp4, file:///home/leo/Downloads/LNO%20Funeral%20Service%20Intro%281%29.mp4, file:///home/leo/Videos/obs/2026-06-25_17-53-33.mkv, file:///home/leo/Videos/obs/2026-06-25_02-23-36.mkv, file:///home/leo/Videos/obs/2026-06-25_01-57-36.mov, file:///home/leo/Videos/obs/2026-06-25_02-16-12.mkv, file:///home/leo/Videos/obs/2026-06-25_01-56-07.mov, file:///home/leo/Videos/converted/Lnostudios%20Intro.mp4, file:///home/leo/Downloads/Mary%20Valery/Copy%20of%20Copy%20of%20life%20in%20photos%20.mp4, file:///home/leo/Downloads/Mary%20Valery/Copy%20of%20LNO%20Lower%20Thirds.mp4, file:///home/leo/Downloads/Mary%20Valery/LNO%20Burial%20Service%20Intro.mp4, file:///home/leo/Downloads/Mary%20Valery/LNO%20Funeral%20Service%20Intro.mp4, file:///home/leo/Downloads/Mary%20Valery/LNO%20Stay%20Tuned%20-%20F.mp4, file:///home/leo/Downloads/Mary%20Valery/Thank%20You.mp4, file:///home/leo/Videos/convert_queue/Adventist%20Funeral_001_Program_003_3.mp4, file:///run/media/leo/LUMIX/Rose%20Zita%20Joseph/Adventist%20Funeral_001_Program_003_0.mp4
times=50883, 0, 0, 0, 67564, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 77216, 0, 0, 0, 0, 0, 0, 0, 0, 0, 41300, 31566, 0, 0, 2402763
